// Package attachments owns explicit, owner-scoped uploads and their derived evidence.
// User filenames are display-only; stored paths are generated by the server.
package attachments

import (
	"archive/zip"
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/google/uuid"
)

var (
	ErrNotFound        = errors.New("attachment not found")
	ErrNotReady        = errors.New("attachment is not ready")
	ErrInvalidState    = errors.New("attachment state does not allow this operation")
	ErrMalwareDetected = errors.New("attachment failed malware scan")
)

type Status string

const (
	StatusUploaded   Status = "uploaded"
	StatusProcessing Status = "processing"
	StatusReady      Status = "ready"
	StatusFailed     Status = "failed"
	StatusExpired    Status = "expired"
)

type Attachment struct {
	ID            string    `json:"id"`
	OwnerID       string    `json:"-"`
	OriginalName  string    `json:"name"`
	SHA256        string    `json:"sha256"`
	MIMEType      string    `json:"mime_type"`
	SizeBytes     int64     `json:"size_bytes"`
	StorageKey    string    `json:"-"`
	Status        Status    `json:"status"`
	ErrorReason   string    `json:"error,omitempty"`
	RetainedUntil time.Time `json:"retained_until"`
	ParserVersion string    `json:"parser_version,omitempty"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Block struct {
	Kind      string  `json:"kind"`
	Text      string  `json:"text,omitempty"`
	StartTime float64 `json:"start_time,omitempty"`
	EndTime   float64 `json:"end_time,omitempty"`
}

type Artifact struct {
	ID               string    `json:"id"`
	AttachmentID     string    `json:"attachment_id"`
	OwnerID          string    `json:"-"`
	SourceRef        string    `json:"source_ref"`
	Text             string    `json:"text"`
	Blocks           []Block   `json:"blocks,omitempty"`
	OCRConfidence    *float64  `json:"ocr_confidence,omitempty"`
	Confidence       *float64  `json:"confidence,omitempty"`
	ExtractorVersion string    `json:"extractor_version"`
	ContentHash      string    `json:"content_hash"`
	CreatedAt        time.Time `json:"created_at"`
}

type Processor interface {
	Process(context.Context, string, Attachment) ([]Artifact, string, error)
}

type Scanner interface {
	Scan(context.Context, string) error
}

// CommandScanner invokes an administrator-configured scanner directly without a shell.
// It is suitable for clamscan when the image/host has an up-to-date signature database.
type CommandScanner struct {
	Command     string
	DatabaseDir string
}

func (s CommandScanner) Scan(ctx context.Context, path string) error {
	if strings.TrimSpace(s.Command) == "" {
		return errors.New("malware scanner is not configured")
	}
	args := []string{"--no-summary", "--infected"}
	if strings.TrimSpace(s.DatabaseDir) != "" {
		args = append(args, "--database="+s.DatabaseDir)
	}
	args = append(args, "--", path)
	cmd := exec.CommandContext(ctx, s.Command, args...)
	if err := cmd.Run(); err != nil {
		var exit *exec.ExitError
		if errors.As(err, &exit) && exit.ExitCode() == 1 {
			return ErrMalwareDetected
		}
		return errors.New("malware scanner failed")
	}
	return nil
}

type Repository interface {
	Create(context.Context, Attachment) error
	BeginProcessing(context.Context, string, string, Status) error
	Get(context.Context, string, string) (Attachment, error)
	List(context.Context, string, int) ([]Attachment, error)
	SetStatus(context.Context, string, string, Status, string, string) error
	SaveArtifacts(context.Context, string, string, []Artifact) error
	Artifacts(context.Context, string, string) ([]Artifact, error)
	Delete(context.Context, string, string) error
	Expired(context.Context, time.Time, int) ([]Attachment, error)
}

type Policy struct {
	Root             string
	MaxFileBytes     int64
	MaxPerRequest    int
	Retention        time.Duration
	AllowedMIMETypes []string
}

type Manager struct {
	root      string
	maxBytes  int64
	maxCount  int
	retention time.Duration
	allowed   map[string]bool
	repo      Repository
	processor Processor
	scanner   Scanner
}

const maxContextEvidenceBytes = 60 << 10

func NewManager(policy Policy, repo Repository, processor Processor, scanner Scanner) (*Manager, error) {
	if repo == nil || processor == nil || scanner == nil {
		return nil, errors.New("attachment repository, processor and malware scanner are required")
	}
	if policy.Root == "" {
		return nil, errors.New("attachment storage directory is required")
	}
	if policy.MaxFileBytes <= 0 || policy.MaxPerRequest <= 0 || policy.Retention <= 0 {
		return nil, errors.New("attachment limits must be positive")
	}
	root, err := filepath.Abs(policy.Root)
	if err != nil {
		return nil, fmt.Errorf("resolve attachment storage directory: %w", err)
	}
	if err := os.MkdirAll(root, 0700); err != nil {
		return nil, fmt.Errorf("create attachment storage directory: %w", err)
	}
	allowed := make(map[string]bool, len(policy.AllowedMIMETypes))
	for _, mime := range policy.AllowedMIMETypes {
		allowed[strings.ToLower(strings.TrimSpace(mime))] = true
	}
	return &Manager{root: root, maxBytes: policy.MaxFileBytes, maxCount: policy.MaxPerRequest, retention: policy.Retention, allowed: allowed, repo: repo, processor: processor, scanner: scanner}, nil
}

func (m *Manager) MaxPerRequest() int { return m.maxCount }

func (m *Manager) Upload(ctx context.Context, owner, name, declaredMIME string, source io.Reader) (Attachment, error) {
	if source == nil {
		return Attachment{}, errors.New("attachment content is required")
	}
	if len(owner) > 191 {
		return Attachment{}, errors.New("owner identity is too long")
	}
	file, err := os.CreateTemp(m.root, ".upload-*")
	if err != nil {
		return Attachment{}, fmt.Errorf("create attachment staging file: %w", err)
	}
	tempPath := file.Name()
	defer os.Remove(tempPath)
	if err := file.Chmod(0600); err != nil {
		_ = file.Close()
		return Attachment{}, err
	}
	hasher := sha256.New()
	size, copyErr := io.Copy(io.MultiWriter(file, hasher), io.LimitReader(source, m.maxBytes+1))
	closeErr := file.Close()
	if copyErr != nil {
		return Attachment{}, copyErr
	}
	if closeErr != nil {
		return Attachment{}, closeErr
	}
	if size == 0 {
		return Attachment{}, errors.New("empty attachments are not supported")
	}
	if size > m.maxBytes {
		return Attachment{}, fmt.Errorf("attachment exceeds the %d byte limit", m.maxBytes)
	}
	displayName := safeDisplayName(name)
	ext := strings.ToLower(filepath.Ext(displayName))
	mime, err := validateFile(tempPath, ext, declaredMIME)
	if err != nil {
		return Attachment{}, err
	}
	if len(m.allowed) > 0 && !m.allowed[mime] {
		return Attachment{}, fmt.Errorf("attachment MIME type %q is not allowed", mime)
	}
	if err := m.scanner.Scan(ctx, tempPath); err != nil {
		if errors.Is(err, ErrMalwareDetected) {
			return Attachment{}, ErrMalwareDetected
		}
		return Attachment{}, fmt.Errorf("attachment scan unavailable: %w", err)
	}
	key := uuid.NewString() + ext
	finalPath, err := m.path(key)
	if err != nil {
		return Attachment{}, err
	}
	if err := os.Rename(tempPath, finalPath); err != nil {
		return Attachment{}, fmt.Errorf("store attachment: %w", err)
	}
	_ = os.Chmod(finalPath, 0600)
	now := time.Now().UTC()
	item := Attachment{ID: uuid.NewString(), OwnerID: owner, OriginalName: displayName, SHA256: fmt.Sprintf("%x", hasher.Sum(nil)), MIMEType: mime, SizeBytes: size, StorageKey: key, Status: StatusUploaded, RetainedUntil: now.Add(m.retention), CreatedAt: now, UpdatedAt: now}
	if err := m.repo.Create(ctx, item); err != nil {
		_ = os.Remove(finalPath)
		return Attachment{}, fmt.Errorf("save attachment metadata: %w", err)
	}
	return m.process(ctx, item, StatusUploaded)
}

func (m *Manager) process(ctx context.Context, item Attachment, expected Status) (Attachment, error) {
	if err := m.repo.BeginProcessing(ctx, item.OwnerID, item.ID, expected); err != nil {
		return Attachment{}, err
	}
	filePath, err := m.path(item.StorageKey)
	if err == nil {
		var artifacts []Artifact
		artifacts, item.ParserVersion, err = m.processor.Process(ctx, filePath, item)
		if err == nil && len(artifacts) == 0 {
			err = errors.New("parser produced no usable evidence")
		}
		if err == nil {
			total := 0
			for _, artifact := range artifacts {
				total += len(artifact.Text)
			}
			if total > maxContextEvidenceBytes {
				err = errors.New("parsed evidence exceeds the 60 KiB per-attachment context limit")
			}
		}
		if err == nil {
			for i := range artifacts {
				artifacts[i].ID = uuid.NewString()
				artifacts[i].AttachmentID = item.ID
				artifacts[i].OwnerID = item.OwnerID
				artifacts[i].CreatedAt = time.Now().UTC()
			}
			err = m.repo.SaveArtifacts(ctx, item.OwnerID, item.ID, artifacts)
		}
	}
	status, reason := StatusReady, ""
	if err != nil {
		status, reason = StatusFailed, safeError(err)
	}
	statusCtx, statusCancel := context.WithTimeout(context.WithoutCancel(ctx), 5*time.Second)
	defer statusCancel()
	if updateErr := m.repo.SetStatus(statusCtx, item.OwnerID, item.ID, status, reason, item.ParserVersion); updateErr != nil {
		return Attachment{}, updateErr
	}
	item.Status, item.ErrorReason, item.UpdatedAt = status, reason, time.Now().UTC()
	return item, nil
}

func (m *Manager) Get(ctx context.Context, owner, id string) (Attachment, error) {
	return m.repo.Get(ctx, owner, id)
}

func (m *Manager) List(ctx context.Context, owner string, limit int) ([]Attachment, error) {
	if limit <= 0 || limit > 100 {
		limit = 100
	}
	return m.repo.List(ctx, owner, limit)
}

func (m *Manager) Artifacts(ctx context.Context, owner, id string) ([]Artifact, error) {
	item, err := m.repo.Get(ctx, owner, id)
	if err != nil {
		return nil, err
	}
	if item.Status != StatusReady {
		return nil, ErrNotReady
	}
	return m.repo.Artifacts(ctx, owner, id)
}

func (m *Manager) Retry(ctx context.Context, owner, id string) (Attachment, error) {
	item, err := m.repo.Get(ctx, owner, id)
	if err != nil {
		return Attachment{}, err
	}
	if item.Status != StatusFailed {
		return Attachment{}, ErrInvalidState
	}
	return m.process(ctx, item, StatusFailed)
}

func (m *Manager) Delete(ctx context.Context, owner, id string) error {
	item, err := m.repo.Get(ctx, owner, id)
	if err != nil {
		return err
	}
	path, err := m.path(item.StorageKey)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove attachment file: %w", err)
	}
	return m.repo.Delete(ctx, owner, id)
}

func (m *Manager) CleanupExpired(ctx context.Context, now time.Time, batch int) (int, error) {
	if batch <= 0 || batch > 1000 {
		batch = 100
	}
	items, err := m.repo.Expired(ctx, now, batch)
	if err != nil {
		return 0, err
	}
	removed := 0
	for _, item := range items {
		path, pathErr := m.path(item.StorageKey)
		if pathErr != nil {
			return removed, pathErr
		}
		if removeErr := os.Remove(path); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
			return removed, removeErr
		}
		if deleteErr := m.repo.Delete(ctx, item.OwnerID, item.ID); deleteErr != nil && !errors.Is(deleteErr, ErrNotFound) {
			return removed, deleteErr
		}
		removed++
	}
	return removed, nil
}

func (m *Manager) ContextFor(ctx context.Context, owner string, ids []string) (string, error) {
	ids = uniqueIDs(ids)
	if len(ids) == 0 {
		return "", nil
	}
	if len(ids) > m.maxCount {
		return "", fmt.Errorf("at most %d attachments may be used in one request", m.maxCount)
	}
	var out strings.Builder
	for _, id := range ids {
		item, err := m.repo.Get(ctx, owner, id)
		if err != nil {
			return "", err
		}
		if item.Status != StatusReady {
			return "", ErrNotReady
		}
		artifacts, err := m.repo.Artifacts(ctx, owner, id)
		if err != nil {
			return "", err
		}
		if len(artifacts) == 0 {
			return "", ErrNotReady
		}
		for _, artifact := range artifacts {
			if len(artifact.Text)+len(item.OriginalName)+len(artifact.SourceRef)+64 > 64*1024-out.Len() {
				return "", errors.New("combined attachment evidence exceeds the context limit")
			}
			fmt.Fprintf(&out, "\n[附件 %s，来源 %s，解析器 %s]\n%s\n", item.OriginalName, artifact.SourceRef, artifact.ExtractorVersion, artifact.Text)
		}
	}
	return out.String(), nil
}

func (m *Manager) path(key string) (string, error) {
	if key == "" || filepath.Base(key) != key || strings.ContainsAny(key, `/\\`) {
		return "", errors.New("invalid attachment storage key")
	}
	path := filepath.Join(m.root, key)
	rel, err := filepath.Rel(m.root, path)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", errors.New("attachment storage key escapes storage directory")
	}
	return path, nil
}

func safeDisplayName(name string) string {
	name = strings.ReplaceAll(name, `\`, "/")
	name = filepath.Base(strings.TrimSpace(name))
	var b strings.Builder
	for _, r := range name {
		if !unicode.IsControl(r) {
			b.WriteRune(r)
		}
		if b.Len() >= 240 {
			break
		}
	}
	if strings.TrimSpace(b.String()) == "" || b.String() == "." {
		return "attachment"
	}
	return b.String()
}

func safeError(err error) string {
	message := strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, err.Error())
	if len(message) > 500 {
		message = string([]rune(message)[:min(500, utf8.RuneCountInString(message))])
	}
	return strings.TrimSpace(message)
}

func uniqueIDs(ids []string) []string {
	seen := make(map[string]bool, len(ids))
	out := make([]string, 0, len(ids))
	for _, id := range ids {
		id = strings.TrimSpace(id)
		if id != "" && !seen[id] {
			seen[id] = true
			out = append(out, id)
		}
	}
	return out
}

func validateFile(path, ext, declaredMIME string) (string, error) {
	allowedExtensions := map[string]string{
		".pdf": "application/pdf", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
		".txt": "text/plain", ".csv": "text/csv", ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".mp3": "audio/mpeg", ".wav": "audio/wav", ".m4a": "audio/mp4", ".mp4": "video/mp4",
	}
	mime, ok := allowedExtensions[ext]
	if !ok {
		return "", fmt.Errorf("file extension %q is not supported", ext)
	}
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	var header [512]byte
	n, err := file.Read(header[:])
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	content := header[:n]
	detected := http.DetectContentType(content)
	valid := false
	switch ext {
	case ".pdf":
		valid = strings.HasPrefix(string(content), "%PDF-")
	case ".png":
		valid = strings.HasPrefix(detected, "image/png")
	case ".jpg", ".jpeg":
		valid = strings.HasPrefix(detected, "image/jpeg")
	case ".txt", ".csv":
		valid = !strings.ContainsRune(string(content), 0) && strings.HasPrefix(detected, "text/")
	case ".docx":
		valid = validateOfficeArchive(path, "word/document.xml") == nil
	case ".xlsx":
		valid = validateOfficeArchive(path, "xl/workbook.xml") == nil
	case ".mp3":
		valid = strings.HasPrefix(detected, "audio/mpeg") || (len(content) > 2 && content[0] == 'I' && content[1] == 'D' && content[2] == '3')
	case ".wav":
		valid = len(content) >= 12 && string(content[:4]) == "RIFF" && string(content[8:12]) == "WAVE"
	case ".m4a":
		valid = len(content) >= 12 && string(content[4:8]) == "ftyp" && (strings.Contains(string(content[:32]), "M4A") || strings.Contains(string(content[:32]), "mp42"))
	case ".mp4":
		valid = len(content) >= 12 && string(content[4:8]) == "ftyp"
	}
	if !valid {
		return "", fmt.Errorf("file extension does not match content for %q", ext)
	}
	declared := strings.ToLower(strings.TrimSpace(strings.Split(declaredMIME, ";")[0]))
	if declared != "" && declared != "application/octet-stream" && declared != mime {
		// Browsers often label office archives and text/csv as generic ZIP/text.
		compatible := (ext == ".docx" || ext == ".xlsx") && declared == "application/zip" || (ext == ".csv" && declared == "text/plain") || (ext == ".m4a" && declared == "video/mp4")
		if !compatible {
			return "", fmt.Errorf("declared MIME type does not match file extension (got %q, expected %q)", declared, mime)
		}
	}
	return mime, nil
}

func validateOfficeArchive(path, required string) error {
	archive, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	reader, err := zip.OpenReader(archive)
	if err != nil {
		return err
	}
	defer reader.Close()
	total := uint64(0)
	found := false
	for _, item := range reader.File {
		if strings.HasPrefix(item.Name, "/") || strings.Contains(item.Name, "..") || item.UncompressedSize64 > 16<<20 {
			return errors.New("unsafe office archive entry")
		}
		total += item.UncompressedSize64
		if total > 40<<20 {
			return errors.New("office archive expands beyond the limit")
		}
		if item.Name == required {
			found = true
		}
	}
	if !found {
		return errors.New("required office document part is missing")
	}
	return nil
}
